// build-config.js
//
// Generates js/firebase-config.js from environment variables at build time.
// This is the ONE piece of "build tooling" in an otherwise plain static
// site — Vercel runs this automatically via the Build Command (see README),
// so the real Firebase config values never sit in the repo or get shipped
// as a committed file.
//
// Local testing (Node 20.6+, no extra packages needed):
//   node --env-file=.env.local build-config.js
// On older Node, export the same variables in your shell instead, then run:
//   node build-config.js

const fs = require("fs");
const path = require("path");

const REQUIRED_VARS = [
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_DATABASE_URL",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID",
];

const missing = REQUIRED_VARS.filter((key) => !process.env[key]);
if (missing.length) {
  console.error(`Missing required environment variables: ${missing.join(", ")}`);
  console.error(
    "Set these in your Vercel project's Environment Variables settings " +
      "(or in .env.local for a local build — see README)."
  );
  process.exit(1);
}

const output = `// js/firebase-config.js
// AUTO-GENERATED by build-config.js at build time from environment
// variables — do not edit this file directly (it's gitignored and gets
// overwritten on every build). Change the values in your Vercel project's
// Environment Variables settings (or .env.local locally) instead.

import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getDatabase } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js";

const firebaseConfig = {
  apiKey: "${process.env.FIREBASE_API_KEY}",
  authDomain: "${process.env.FIREBASE_AUTH_DOMAIN}",
  databaseURL: "${process.env.FIREBASE_DATABASE_URL}",
  projectId: "${process.env.FIREBASE_PROJECT_ID}",
  storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${process.env.FIREBASE_APP_ID}",
};

const app = initializeApp(firebaseConfig);
export const db = getDatabase(app);
`;

const outPath = path.join(__dirname, "js", "firebase-config.js");
fs.writeFileSync(outPath, output);
console.log(`Wrote ${outPath}`);
